import type { Metadata } from "next";
import Link from "next/link";
import { CodeBlock } from "../../_docs/CodeBlock";
import styles from "../../_docs/Docs.module.css";
import { DocsShell } from "../../_docs/DocsShell";

export const metadata: Metadata = { title: "Theming" };

const TOC = [
  { id: "layers", label: "Token layers" },
  { id: "presets", label: "Presets and modes" },
  { id: "make", label: "Make a theme" },
  { id: "rule", label: "The one CSS rule" },
];

export default function Theming() {
  return (
    <DocsShell current="/docs/theming" toc={TOC}>
      <h1 className={styles.title}>Theming</h1>
      <p className={styles.lede}>
        Every visual decision in Rime is a CSS custom property. A theme is a short theme.css that changes the values you care about;
        everything else recomputes from them.
      </p>

      <section className={styles.section} id="layers" aria-labelledby="layers-h">
        <h2 id="layers-h" className={styles.h2}>
          Token layers
        </h2>
        <ol className={styles.list}>
          <li>
            <strong>Primitives:</strong> the palette (--brand, --brand-action, --brand-strong, --brand-deep, --brand-soft,
            --support, --danger-base) and its rgb channels (--rgb-brand), fonts, the chart palette.
          </li>
          <li>
            <strong>Semantic:</strong> ink (--ink-*), surfaces and glass (--page-background, --glass-fill, --surface-solid), lines,
            status, focus, gradients.
          </li>
          <li>
            <strong>Scales:</strong> radius (--r-*), --density, control heights, borders, shadows, blurs, motion.
          </li>
          <li>
            <strong>Per component:</strong> --button-radius, --input-height-md, --table-head-fill and the rest. Undeclared by default:
            each module reads them with a fallback, so setting one restyles every instance. Each component page lists its own.
          </li>
        </ol>
      </section>

      <section className={styles.section} id="presets" aria-labelledby="presets-h">
        <h2 id="presets-h" className={styles.h2}>
          Presets and modes
        </h2>
        <p className={styles.note}>
          Theme = preset x mode. Rime Default (frosted glass in Frost blue) is the base; data-theme=&quot;flat&quot; switches to Rime
          Flat (opaque, small radii, no blur). Dark mode is data-mode=&quot;dark&quot; or the .dark class, with either preset.
        </p>
        <CodeBlock code={`<html data-theme="flat" class="dark">  {/* Rime Flat, dark mode */}`} />
      </section>

      <section className={styles.section} id="make" aria-labelledby="make-h">
        <h2 id="make-h" className={styles.h2}>
          Make a theme
        </h2>
        <p className={styles.note}>
          Open <Link href="/themes">Rime Studio</Link>: start from a preset, drop in a logo or screenshot to extract a palette, tune
          shape, glass, shadows and hover, check contrast in both modes, save it by name and export theme.css. Load it after
          tokens.css.
        </p>
        <CodeBlock
          language="css"
          label="app/styles/theme.css"
          code={`/* Acme: generated by Rime Studio. Base: Rime Default. */
:root {
  --brand: #0f9b8e;
  --brand-action: #0b7a70;
  --brand-strong: #075f57;
  --rgb-brand: 15, 155, 142;
  --r-md: 6px;
  --button-radius: 999px;
}

.dark, [data-mode="dark"] {
  --brand: #3fc6b8;
  --rgb-brand: 63, 198, 184;
}`}
        />
      </section>

      <section className={styles.section} id="rule" aria-labelledby="rule-h">
        <h2 id="rule-h" className={styles.h2}>
          The one CSS rule
        </h2>
        <p className={styles.note}>
          A custom property resolves var() where it is declared. --wash-hover is rgba(var(--rgb-brand), 0.05) on :root, so a theme
          that changes --rgb-brand must also be declared on :root (then the wash recomputes), or redeclare the composites it
          affects. The Studio&apos;s default export (only what changed, at :root) is right.
        </p>
      </section>
    </DocsShell>
  );
}
