// Writes the component docs as markdown into docs/ui/, for AI agents (and
// people) reading the repo rather than the running site:
//
//   node scripts/export-ui-docs.mjs
//
// The text is exactly what /llms.txt, /llms-full.txt and /md/*.md
// serve: both come from components/ui/_registry/markdown.ts. The registry is
// plain TypeScript with no JSX, so this transpiles it to a temp folder with
// the TypeScript compiler and imports it; no dev server needed. Run it after
// changing a registry entry, and after scripts/gen-ui-registry.mjs.
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";
import { pathToFileURL } from "node:url";
import ts from "typescript";

const SRC = "components/ui/_registry";
const OUT = "docs/ui";

const walk = (dir, out = []) => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (p.endsWith(".ts")) out.push(p);
  }
  return out;
};

const tmp = mkdtempSync(join(tmpdir(), "ui-docs-"));
try {
  for (const file of walk(SRC)) {
    const { outputText } = ts.transpileModule(readFileSync(file, "utf8"), {
      compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022, verbatimModuleSyntax: false },
      fileName: file,
    });
    // Relative imports gain the extension Node's ESM loader needs.
    const js = outputText.replace(/(from\s+["'])(\.{1,2}\/[^"']+)(["'])/g, (_, a, path, b) => {
      const target = join(dirname(file), path);
      const isDir = (() => {
        try {
          return statSync(target).isDirectory();
        } catch {
          return false;
        }
      })();
      return `${a}${path}${isDir ? "/index" : ""}.mjs${b}`;
    });
    const out = join(tmp, relative(SRC, file)).replace(/\.ts$/, ".mjs");
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, js);
  }

  const md = await import(pathToFileURL(join(tmp, "markdown.mjs")).href);
  const reg = await import(pathToFileURL(join(tmp, "index.mjs")).href);

  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(join(OUT, "components"), { recursive: true });
  const header = "<!-- GENERATED by scripts/export-ui-docs.mjs from components/ui/_registry. Edit the registry, not this file. -->\n\n";
  // Links point at the repo copies here, and at / on the running site.
  writeFileSync(join(OUT, "llms.txt"), md.llmsIndex("").replaceAll("](/md/", "](components/").replaceAll("](/llms-full.txt)", "](llms-full.txt)"));
  writeFileSync(join(OUT, "llms-full.txt"), md.llmsFull());
  writeFileSync(join(OUT, "components", "theme.md"), header + md.THEME_MARKDOWN);
  writeFileSync(join(OUT, "components", "patterns.md"), header + md.patternsMarkdown());
  for (const entry of reg.REGISTRY) writeFileSync(join(OUT, "components", `${entry.slug}.md`), header + md.entryToMarkdown(entry));
  console.log(`docs/ui: llms.txt, llms-full.txt and ${reg.REGISTRY.length + 2} pages`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
