import type { RegistryEntry } from "../types";

export const FEEDBACK: RegistryEntry[] = [
  {
    slug: "alert",
    name: "Alert",
    category: "Feedback",
    summary: "An inline message in a tone (info, success, warning, danger) or a quiet legal box for fixed wording, with an action and dismiss.",
    description: ["Alert sits in the flow of a page or form. It carries a title, body, an action (a retry), a badge and an optional reference code for approved wording. live makes it announce when it appears."],
    importLine: `import { Alert } from "@/components/ui";`,
    usage: `<Alert tone="warning" title="Payment is processing">We will email you when the bank confirms it.</Alert>`,
    props: ["Alert"],
    css: ["components/ui/Alert/Alert.module.css"],
    examples: [{ id: "default", title: "Tones", code: `<Alert tone="info" title="Heads up">…</Alert>\n<Alert tone="danger" title="Couldn't save" action={<Button size="sm" variant="secondary">Try again</Button>} />` }],
    accessibility: ["live renders role=\"alert\" (danger and warning) or role=\"status\" (the rest); without live it is plain content, so it is not re-announced on every render."],
    dos: ["Say what happened and what to do next."],
    donts: ["Don't use an Alert for transient confirmation; that is a toast."],
    depth: "summary",
  },
  {
    slug: "toast",
    name: "Toast",
    category: "Feedback",
    summary: "Frosted toasts for success, error, info and in-flight work, stacked as a deck that fans out on hover.",
    description: [
      "Mount ToastProvider once in the root layout and call useToast(). success and info leave after 5 seconds with a timer rule; error and loading stay until dismissed or settled. toast.promise shows loading, then success or error when the promise settles.",
    ],
    importLine: `import { useToast } from "@/components/ui";`,
    usage: `const toast = useToast();
await toast.promise(save(), { loading: "Saving…", success: "Saved", error: "Couldn't save" });`,
    props: [],
    css: ["components/ui/Toast/Toast.module.css"],
    examples: [{ id: "open", title: "The stack", description: "ToastStackPreview draws the real stack in place, with no timers and no live region: loading, an error with an action, and a success.", code: `<ToastStackPreview
  expanded
  items={[
    { id: 1, tone: "loading", title: "Saving changes…" },
    { id: 2, tone: "error", title: "Couldn't send", description: "Check your connection.", action: { label: "Retry", onClick: retry } },
    { id: 3, tone: "success", title: "Invoice sent", description: "INV-1042 is on its way to Jane Cooper." },
  ]}
/>` }, { id: "default", title: "Tones", code: `toast.success("Invoice sent", { description: "INV-1042 is on its way to Jane Cooper." });\ntoast.error("Couldn't send", { action: { label: "Retry", onClick: retry } });` }],
    accessibility: ["The stack sits in a region labelled \"Notifications\" with a polite live list, and stays live while a Modal makes the rest of the page inert.", "Hover or focus inside fans the stack out and pauses every timer; toasts never take focus."],
    dos: ["Confirm what was done, with the record's name or reference."],
    donts: ["Don't put the only copy of important information in a toast."],
    depth: "summary",
  },
  {
    slug: "spinner",
    name: "Spinner",
    category: "Feedback",
    summary: "A small brand-tinted spinner for in-flight work inside buttons, fields and panels.",
    description: ["Spinner is decorative unless given a label. Buttons and IconButtons show it themselves when loading."],
    importLine: `import { Spinner } from "@/components/ui";`,
    usage: `<Spinner label="Loading invoices" />`,
    props: ["Spinner"],
    css: ["components/ui/Spinner/Spinner.module.css"],
    examples: [{ id: "default", title: "Sizes", code: `<Spinner size={14} />\n<Spinner size={20} label="Loading" />` }],
    accessibility: ["With label it is wrapped in role=\"status\" with the label as text; without, it is decorative."],
    dos: ["Prefer skeletons for content that is loading."],
    donts: ["Don't spin a whole page; show its shape."],
    depth: "summary",
  },
  {
    slug: "empty-state",
    name: "EmptyState",
    category: "Feedback",
    summary: "What an empty list means and what to do next: default, positive (all done) and filtered tones.",
    description: ["EmptyState never says just \"No data\". It names why the space is empty and offers the next step as an action. compact fits inside a Table."],
    importLine: `import { EmptyState } from "@/components/ui";`,
    usage: `<EmptyState title="No projects yet" description="Create a project to start tracking work." action={<Button href="/projects/new">New project</Button>} />`,
    props: ["EmptyState"],
    css: ["components/ui/EmptyState/EmptyState.module.css"],
    examples: [{ id: "default", title: "Tones", code: `<EmptyState tone="positive" title="All caught up" description="Nothing is waiting for review." />` }],
    accessibility: ["The icon is decorative; the title and description are plain text, so put the empty state under the heading of the list it belongs to."],
    dos: ["Use tone=\"filtered\" with a clear-filters action when filters emptied the list."],
    donts: ["Never ship a bare \"No data\"."],
    depth: "summary",
  },
  {
    slug: "tooltip",
    name: "Tooltip and Toggletip",
    category: "Overlays",
    summary: "Hover and focus tooltips (dark one-liners or light rich cards) and click-to-open toggletips for help.",
    description: ["Tooltip labels a control on hover and focus after a short delay; it can show a keyboard shortcut and only appear when text is truncated. Toggletip is an info button that opens a small panel on click, for help text people need to read."],
    importLine: `import { Toggletip, Tooltip } from "@/components/ui";`,
    usage: `<Tooltip content="Print invoice"><IconButton label="Print" icon={<IconPrinter size={17} />} /></Tooltip>`,
    props: ["Tooltip", "Toggletip"],
    css: ["components/ui/Tooltip/Tooltip.module.css"],
    examples: [{ id: "open", title: "Open", description: "inline shows the bubble and the toggletip panel open beside their triggers, in place.", code: `<Tooltip inline content="Print invoice" shortcut={["Ctrl", "P"]}>…</Tooltip>
<Toggletip inline label="About seats" title="Seats">Each plan includes five seats.</Toggletip>` }, { id: "default", title: "Tooltip and toggletip", code: `<Tooltip content="Copy reference" shortcut={["Ctrl", "C"]}>…</Tooltip>\n<Toggletip label="About seats">Each plan includes five seats.</Toggletip>` }],
    accessibility: ["Tooltip content is the trigger's description (aria-describedby), shown on focus too, dismissed with Esc.", "Toggletip content is announced through a live region when opened."],
    dos: ["Keep tooltips to a few words."],
    donts: ["Don't put interactive content in a Tooltip; use a Toggletip."],
    depth: "summary",
  },
  {
    slug: "impact-preview",
    name: "ImpactPreview",
    category: "Feedback",
    summary: "What a destructive action will change, row by row, before it is confirmed.",
    description: ["ImpactPreview lists the consequences of an action (projects reassigned, sign-ins revoked) with severities, named affected records, and loading, error and nothing-affected states. TypeToConfirmModal embeds it."],
    importLine: `import { ImpactPreview } from "@/components/ui";`,
    usage: `<ImpactPreview items={[{ id: "a", severity: "destructive", title: "Signed out everywhere" }]} />`,
    props: ["ImpactPreview"],
    css: ["components/ui/ImpactPreview/ImpactPreview.module.css"],
    examples: [{ id: "default", title: "Default", code: `<ImpactPreview statement="This action cannot be undone" items={ITEMS} />` }],
    accessibility: ["A list with a heading; severities are written out, not only coloured."],
    dos: ["State each row as an outcome: \"3 projects are reassigned\"."],
    donts: ["Don't hide consequences behind a disclosure."],
    depth: "summary",
  },
];
